### ISSUE TITLE
@Vality (unrelated to repository)

### ISSUE THREAD

**Issue by simonmeister** [Vality/DResMan#1]
Hi @Vality, 

we are a young startup building VR technology for collaborative workspaces (first purpose build headset release in 2020). We initially had the working name Omnence, however we are rebranding to Vality (we also were able to secure vality.com). Would it be possible for you to change your GitHub username so that we could have the fitting GitHub handle, or is it very important to you? We would be very happy if this would be possible.

Thanks,
Simon

**Comment by Vality** [comment]
Hi there,

Vality is the name of one the main characters in a collection of fictional
stories, art and comic franchise I own.

I've used the handle extensively for many years now on a very wide range of
platforms and am known by that on various social networks, brands and other
areas.

Although I have no problem with your company using the term (as it sounds
like your concept has nothing to do with how I use the name), I would
really rather not abandon it myself as it's important to my brand and has
been for many years.

Additionally I'm known by that name in the Linux Kernel development
community and have used it as a handle on tech groups such as stack
overflow for years.

As much as your company and idea sounds really interesting and I hope you
all do well I would really prefer not to abandon the handle and brand im
known by across so many communities.

I'm sorry for the dissapointing answer and really hope all the best for
your group.

Kind regards,
Val

**Comment by simonmeister** [comment]
Thanks a lot for taking your time to answer. I understand and of course we have no problem with using a different GitHub handle. 

Simon
